version: '3'
services:
  mitmproxy1:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy1
    ports:
      - "8080:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3081 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy2:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy2
    ports:
      - "8082:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3082 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy3:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy3
    ports:
      - "8084:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3083 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy4:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy4
    ports:
      - "8086:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3084 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy5:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy5
    ports:
      - "8088:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3085 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy6:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy6
    ports:
      - "8090:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3086 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy7:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy7
    ports:
      - "8092:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3087 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy8:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy8
    ports:
      - "8094:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3088 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy9:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy9
    ports:
      - "8096:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3089 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy10:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy10
    ports:
      - "8098:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3090 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy11:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy11
    ports:
      - "8100:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3091 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy12:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy12
    ports:
      - "8102:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3092 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy13:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy13
    ports:
      - "8104:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3093 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
  mitmproxy14:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy14
    ports:
      - "8105:8080"
    command: >
      sh -c "mitmdump --mode upstream:http://fineproxy.xyz:3094 --upstream-auth PPR027ZAFX1:zAnMZB5W2YAALy"
    stdin_open: true
    tty: true
    networks:
      - mitmproxy_net
networks:
  mitmproxy_net:
    driver: bridge
